// generated_projects/4d991389-b009-490f-a041-fd7dc1706ef9/src/App.vue
<template>
  <div class="light min-h-screen bg-gray-50 dark:bg-gray-900">
    <div class="container mx-auto px-4">
    <Features />
    <Footer />
    <CTA />
    <Hero />
    </div>
  </div>
</template>

<script setup lang="ts">
import Features from './components/Features.vue'
import Footer from './components/Footer.vue'
import CTA from './components/CTA.vue'
import Hero from './components/Hero.vue'
</script>

<style scoped>
</style>

// generated_projects/c7288dda-168c-4a21-b21a-61ac91aac2b0/src/App.tsx
import React from "react"
import MainContent from "./components/MainContent"
import Header from "./components/Header"
import Sidebar from "./components/Sidebar"

function App() {
  return (
    <div className="light min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4">
      <MainContent />
      <Header />
      <Sidebar />
      </div>
    </div>
  )
}

export default App
