// generated_projects/4d991389-b009-490f-a041-fd7dc1706ef9/src/App.vue
<template>
  <div class="light min-h-screen bg-gray-50 dark:bg-gray-900">
    <div class="container mx-auto px-4">
    <Features />
    <Footer />
    <CTA />
    <Hero />
    </div>
  </div>
</template>

<script setup lang="ts">
import Features from './components/Features.vue'
import Footer from './components/Footer.vue'
import CTA from './components/CTA.vue'
import Hero from './components/Hero.vue'
</script>

<style scoped>
</style>

// extracted-project/src/App.tsx
import React from "react"
import PostDetail from "./components/PostDetail"
import PostList from "./components/PostList"
import Footer from "./components/Footer"
import Header from "./components/Header"

function App() {
  return (
    <div className="light min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4">
      <PostDetail />
      <PostList />
      <Footer />
      <Header />
      </div>
    </div>
  )
}

export default App
