// extracted-project/src/components/Footer.tsx
import React from 'react'

interface FooterProps {
  className?: string
}

const Footer: React.FC<FooterProps> = ({ className = '' }) => {
  return (
    <div className="p-4 border {className}">
      <h2 className="text-xl font-semibold mb-2">Footer</h2>
      <p className="text-gray-600 dark:text-gray-300">
        This is the Footer component.
      </p>
    </div>
  )
}

export default Footer

// generated_projects/4d991389-b009-490f-a041-fd7dc1706ef9/src/Footer.vue
<template>
  <div :class="['p-4 rounded-lg shadow-sm', className]">
    <h2 class="text-xl font-semibold mb-2">Footer</h2>
    <p class="text-gray-600 dark:text-gray-300">
      This is the Footer component.
    </p>
  </div>
</template>

<script setup lang="ts">
interface Props {
  className?: string
}

withDefaults(defineProps<Props>(), {
  className: ''
})
</script>

<style scoped>
</style>
