// generated_projects/fce222ff-c632-47d7-990f-c34b973f1b0e/src/components/Hero.tsx
import React from 'react'

interface HeroProps {
  className?: string
}

const Hero: React.FC<HeroProps> = ({ className = '' }) => {
  return (
    <div className="p-4 rounded-lg shadow-sm {className}">
      <h2 className="text-xl font-semibold mb-2">Hero</h2>
      <p className="text-gray-600 dark:text-gray-300">
        This is the Hero component.
      </p>
    </div>
  )
}

export default Hero

// generated_projects/4d991389-b009-490f-a041-fd7dc1706ef9/src/Hero.vue
<template>
  <div :class="['p-4 rounded-lg shadow-sm', className]">
    <h2 class="text-xl font-semibold mb-2">Hero</h2>
    <p class="text-gray-600 dark:text-gray-300">
      This is the Hero component.
    </p>
  </div>
</template>

<script setup lang="ts">
interface Props {
  className?: string
}

withDefaults(defineProps<Props>(), {
  className: ''
})
</script>

<style scoped>
</style>
