// generated_projects/4d991389-b009-490f-a041-fd7dc1706ef9/src/App.vue
<template>
  <div class="light min-h-screen bg-gray-50 dark:bg-gray-900">
    <div class="container mx-auto px-4">
    <Features />
    <Footer />
    <CTA />
    <Hero />
    </div>
  </div>
</template>

<script setup lang="ts">
import Features from './components/Features.vue'
import Footer from './components/Footer.vue'
import CTA from './components/CTA.vue'
import Hero from './components/Hero.vue'
</script>

<style scoped>
</style>

// generated_projects/fce222ff-c632-47d7-990f-c34b973f1b0e/src/App.tsx
import React from "react"
import "./index.css"
import Footer from "./components/Footer"
import Header from "./components/Header"
import Contact from "./components/Contact"
import Hero from "./components/Hero"
import ProjectCard from "./components/ProjectCard"

function App() {
  return (
    <div className="light min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4">
      <Footer />
      <Header />
      <Contact />
      <Hero />
      <ProjectCard />
      </div>
    </div>
  )
}

export default App
